In [24]:
import pandas as pd

In [25]:
df = pd.read_csv("../data/clientes.csv")
df

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,dtCriacao,dtAtualizacao
0,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,686,NaN,NaN
1,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,NaN,NaN
2,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,NaN,NaN
3,0033b737-8235-4c0f-9801-dc4ca185af00,0,1,0,0,0,1090,0000-00-00 00:00:00.000,2025-02-19 12:48:24.632
4,00684343-40b5-4ce7-b2e8-71a5340973bf,0,0,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2431,fecbdf63-3bf4-44e5-8b1a-0acc9d963603,0,0,0,0,0,111,NaN,NaN
2432,ff07d926-f09e-420b-bebf-3dba02ae5dff,0,1,0,0,0,54,2025-01-21 11:49:58.172,2025-02-28 11:55:04.999
2433,ff1ceaef-650c-422b-bdc3-6984e29e7aa5,0,0,0,0,0,162,NaN,NaN
2434,ff2cabd3-3316-4b3f-8494-c25f95e90524,0,1,0,0,0,57,2025-02-10 11:12:30.631,2025-02-10 12:37:47.892
2435,ff4909ad-4e52-4767-a6fc-0fbd76e37857,0,0,0,0,0,50,NaN,NaN

In [26]:
df["qtdePontos"].astype("int").astype("str")

0        686
1         50
2          2
3       1090
4          0
        ...
2431     111
2432      54
2433     162
2434      57
2435      50
Name: qtdePontos, Length: 2436, dtype: object

In [27]:
replace = {"0000-00-00 00:00:00.000": "2024-02-01 09:00:00.000"}
df["dtCriacao"] = pd.to_datetime(df["dtCriacao"].replace(replace))
df

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,dtCriacao,dtAtualizacao
0,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,686,NaT,NaN
1,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,NaT,NaN
2,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,NaT,NaN
3,0033b737-8235-4c0f-9801-dc4ca185af00,0,1,0,0,0,1090,2024-02-01 09:00:00.000,2025-02-19 12:48:24.632
4,00684343-40b5-4ce7-b2e8-71a5340973bf,0,0,0,0,0,0,NaT,NaN
...,...,...,...,...,...,...,...,...,...
2431,fecbdf63-3bf4-44e5-8b1a-0acc9d963603,0,0,0,0,0,111,NaT,NaN
2432,ff07d926-f09e-420b-bebf-3dba02ae5dff,0,1,0,0,0,54,2025-01-21 11:49:58.172,2025-02-28 11:55:04.999
2433,ff1ceaef-650c-422b-bdc3-6984e29e7aa5,0,0,0,0,0,162,NaT,NaN
2434,ff2cabd3-3316-4b3f-8494-c25f95e90524,0,1,0,0,0,57,2025-02-10 11:12:30.631,2025-02-10 12:37:47.892
2435,ff4909ad-4e52-4767-a6fc-0fbd76e37857,0,0,0,0,0,50,NaT,NaN