In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/transacao_produto.csv", sep=",")
df

,idTransacaoProduto,idTransacao,idProduto,qtdeProduto,VlProduto
0,000026d0-4d4e-4fed-934a-9e5b26d9e379,d59d9859-8fb9-41cc-a296-be38c4dce8e4,5,1,1
1,00002f54-dd03-4b3f-ade0-22c3e61df8c2,519241fd-2676-49b2-8e74-0acc09a08f69,5,1,1
2,00006a7d-c83a-44ca-aad9-e8a2a2f1b64d,73993c42-d18f-4f51-82c4-25e13c29962c,11,1,50
3,00013246-e90f-41a9-b4cc-c9e905fd520b,90bbc76e-f93e-494d-a7ba-5d6e971a88b8,5,1,1
4,000146b9-3ecc-4a08-be5a-e8127cf7d9b3,f6efc1f8-4e45-42d2-bb8f-c46fac06a1d5,5,1,1
...,...,...,...,...,...
182836,fffd0ca8-a6c9-4776-ba7a-2463dfeca712,02c3bd7e-adf3-4510-b7b8-25df934c1e61,5,1,1
182837,fffd40ea-e039-4654-b0b6-0b86e5b2a4e5,30e6ae30-e2b5-46bc-a5c9-a92c4900d548,5,1,1
182838,fffd9569-31e6-4515-8494-4edeabc0cfc2,6baf63b1-d05a-419d-a84f-abdf6906fef8,11,1,50
182839,fffe7e68-c450-4025-9469-e5cbe7699b49,90f7149b-5794-4d49-9239-c3bddb5b0980,5,1,1
182840,ffff210a-2594-42fa-8d85-c97483817542,4d7c74c0-5ca0-4786-823b-b393d505c2e6,5,1,1

In [5]:
# Verificar Produtos com id 5 ou 11
df[df["idProduto"].isin([5, 11])]

,idTransacaoProduto,idTransacao,idProduto,qtdeProduto,VlProduto
0,000026d0-4d4e-4fed-934a-9e5b26d9e379,d59d9859-8fb9-41cc-a296-be38c4dce8e4,5,1,1
1,00002f54-dd03-4b3f-ade0-22c3e61df8c2,519241fd-2676-49b2-8e74-0acc09a08f69,5,1,1
2,00006a7d-c83a-44ca-aad9-e8a2a2f1b64d,73993c42-d18f-4f51-82c4-25e13c29962c,11,1,50
3,00013246-e90f-41a9-b4cc-c9e905fd520b,90bbc76e-f93e-494d-a7ba-5d6e971a88b8,5,1,1
4,000146b9-3ecc-4a08-be5a-e8127cf7d9b3,f6efc1f8-4e45-42d2-bb8f-c46fac06a1d5,5,1,1
...,...,...,...,...,...
182836,fffd0ca8-a6c9-4776-ba7a-2463dfeca712,02c3bd7e-adf3-4510-b7b8-25df934c1e61,5,1,1
182837,fffd40ea-e039-4654-b0b6-0b86e5b2a4e5,30e6ae30-e2b5-46bc-a5c9-a92c4900d548,5,1,1
182838,fffd9569-31e6-4515-8494-4edeabc0cfc2,6baf63b1-d05a-419d-a84f-abdf6906fef8,11,1,50
182839,fffe7e68-c450-4025-9469-e5cbe7699b49,90f7149b-5794-4d49-9239-c3bddb5b0980,5,1,1
182840,ffff210a-2594-42fa-8d85-c97483817542,4d7c74c0-5ca0-4786-823b-b393d505c2e6,5,1,1

In [7]:
clientes = pd.read_csv("../data/clientes.csv", sep=",")
clientes

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,dtCriacao,dtAtualizacao
0,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,686,NaN,NaN
1,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,NaN,NaN
2,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,NaN,NaN
3,0033b737-8235-4c0f-9801-dc4ca185af00,0,1,0,0,0,1090,0000-00-00 00:00:00.000,2025-02-19 12:48:24.632
4,00684343-40b5-4ce7-b2e8-71a5340973bf,0,0,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2431,fecbdf63-3bf4-44e5-8b1a-0acc9d963603,0,0,0,0,0,111,NaN,NaN
2432,ff07d926-f09e-420b-bebf-3dba02ae5dff,0,1,0,0,0,54,2025-01-21 11:49:58.172,2025-02-28 11:55:04.999
2433,ff1ceaef-650c-422b-bdc3-6984e29e7aa5,0,0,0,0,0,162,NaN,NaN
2434,ff2cabd3-3316-4b3f-8494-c25f95e90524,0,1,0,0,0,57,2025-02-10 11:12:30.631,2025-02-10 12:37:47.892
2435,ff4909ad-4e52-4767-a6fc-0fbd76e37857,0,0,0,0,0,50,NaN,NaN

In [ ]:
# Filtrar por dtCriacao nao é nulo
clientes[clientes["dtCriacao"].notnull()]

# Existe uma forma de negar a afirmação, usando o operador ~

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,dtCriacao,dtAtualizacao
3,0033b737-8235-4c0f-9801-dc4ca185af00,0,1,0,0,0,1090,0000-00-00 00:00:00.000,2025-02-19 12:48:24.632
6,00a6d4c8-38e5-4e92-981e-4e4ac5084546,1,0,0,0,0,6637,0000-00-00 00:00:00.000,2025-02-27 12:28:58.378
9,0122142b-464c-414a-9aad-e901f492a1a3,0,1,0,0,0,119,2025-01-10 12:01:26.743,2025-02-10 11:09:05.041
12,014491f5-caa3-4122-be69-a31411ad4bd7,0,1,0,0,0,154,0000-00-00 00:00:00.000,2024-11-25 12:29:46.067
13,0147f062-0e6c-46a9-a66d-d0bc4d651a73,0,1,0,0,0,50,2025-01-08 11:52:29.269,2025-01-08 11:52:39.201
...,...,...,...,...,...,...,...,...,...
2424,fdac1c1e-bd14-4f14-8fbd-e4265e3e7ac7,0,1,0,0,0,554,2025-02-10 11:09:21.094,2025-02-21 11:37:23.844
2426,fe391f8e-c2eb-4bd9-b8a5-e284151deb6a,0,1,0,0,0,100,2025-02-11 11:01:12.243,2025-02-19 11:06:57.941
2429,feb1a34d-202a-4224-a1b3-0e737b12dd4d,0,1,0,0,0,2316,0000-00-00 00:00:00.000,2024-12-11 12:41:29.958
2432,ff07d926-f09e-420b-bebf-3dba02ae5dff,0,1,0,0,0,54,2025-01-21 11:49:58.172,2025-02-28 11:55:04.999
2434,ff2cabd3-3316-4b3f-8494-c25f95e90524,0,1,0,0,0,57,2025-02-10 11:12:30.631,2025-02-10 12:37:47.892